### ISSUE TITLE
NoMethodError: undefined method `empty?' for nil:NilClass

### ISSUE THREAD

**Issue by yoonwaiyan** [guilhermesad/rspotify#109]
Tried to access playlists but no luck :(

Request:
```ruby
RSpotify::Playlist.find('yoonwaiyan', '<my_playlist_id>')
```

Full stack:
```ruby
NoMethodError: undefined method `empty?' for nil:NilClass
	from /Users/user/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspotify-1.19.1/lib/rspotify/connection.rb:71:in `send_request'
	from /Users/user/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspotify-1.19.1/lib/rspotify/connection.rb:36:in `block (2 levels) in singleton class'
	from /Users/user/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspotify-1.19.1/lib/rspotify/connection.rb:48:in `resolve_auth_request'
	from /Users/user/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspotify-1.19.1/lib/rspotify/playlist.rb:55:in `find'
	from (irb):2
	from /Users/user/.rbenv/versions/2.2.2/bin/irb:11:in `<main>'
```

**Comment by guilhermesad** [comment]
Have you tried [`RSpotify.authenticate`](http://www.rubydoc.info/github/guilhermesad/rspotify/master/RSpotify.authenticate)? Please have a look in [here](https://github.com/guilhermesad/rspotify#usage).

**Comment by yoonwaiyan** [comment]
Works now, probably forgot I have to authenticate as my gist didn't include the authentication. I think it's a better idea to return a helpful message instead of raising errors without knowing any specific reason though.
