### ISSUE TITLE
Cannot add track to playlist

### ISSUE THREAD

**Issue by jefrice** [guilhermesad/rspotify#163]
Error message: 
```
NoMethodError - undefined method `first' for #<RSpotify::Track:0x00007fda250d34a8>:
  app/models/item.rb:129:in `get_spotify_info'
  app/controllers/playlists_controller.rb:124:in `add_to_playlist'
  app/controllers/application_controller.rb:8:in `collect_metrics'
```

Here is the code I am using:

```
              spotify_tracks   = RSpotify::Track.find(@track.spotify_id)
              tmp_pl            = Playlist.find(self.itemable_id)
              tmp_user          = User.find(tmp_pl.user_id)
              tmp_s_user_hash   = eval(tmp_user.spotify_user)
              tmp_suid          = tmp_s_user_hash['uid']
              @spotify_playlist = RSpotify::Playlist.find(tmp_suid, tmp_pl.spotify_id)
129        @spotify_playlist.add_tracks!(spotify_tracks)
```

I have verified (multiple times) that I am authenticated with spotify along with the proper scope settings. 

HELP!

**Comment by jefrice** [comment]
If i change the code to something like the example, i.e. 

```
        spotify_tracks  = RSpotify::Track.search('Know')
        tmp_pl          = Playlist.find(self.itemable_id)
        tmp_user        = User.find(tmp_pl.user_id)
        tmp_s_user_hash = eval(tmp_user.spotify_user)
        tmp_suid = tmp_s_user_hash['uid']
        @spotify_playlist = RSpotify::Playlist.find(tmp_suid, tmp_pl.spotify_id)
        @spotify_playlist.add_tracks!(spotify_tracks)
```

then I get this error:

```
NameError - uninitialized class variable @@users_credentials in RSpotify::User:
  app/models/item.rb:133:in `get_spotify_info'
  app/controllers/playlists_controller.rb:124:in `add_to_playlist'
  app/controllers/application_controller.rb:8:in `collect_metrics'
```

**Comment by jefrice** [comment]
It works with 
spotify_tracks  = RSpotify::Track.search('Know')
but NOT with 
spotify_tracks = RSpotify::Track.find(@track.spotify_id)

**Comment by jefrice** [comment]
OK - I feel like a prize idiot -- BUT here is the solution. When you are using Track.find for a single track rather than an array of tracks, you have to wrap your variable with an Array, i.e.

`spotify_track = Array.wrap(RSpotify::Track.find(@track.spotify_id))`

This works like a charm. You might consider adding this tip to the documentation.
