### ISSUE TITLE
Options are nil when fetching playlists

### ISSUE THREAD

**Issue by fwcd** [guilhermesad/rspotify#270]
A [tool](https://github.com/fwcd/drum) I built using this library has begun crashing for me two days ago:

```
/opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/gems/3.3.0/gems/rspotify-2.12.4/lib/rspotify/playlist.rb:97:in `initialize': undefined method `[]' for nil (NoMethodError)

      @collaborative = options['collaborative']
                              ^^^^^^^^^^^^^^^^^
	from /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/gems/3.3.0/gems/rspotify-2.12.4/lib/rspotify/user.rb:285:in `new'
	from /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/gems/3.3.0/gems/rspotify-2.12.4/lib/rspotify/user.rb:285:in `block in playlists'
	from /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/gems/3.3.0/gems/rspotify-2.12.4/lib/rspotify/user.rb:285:in `map'
	from /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/gems/3.3.0/gems/rspotify-2.12.4/lib/rspotify/user.rb:285:in `playlists'
        from /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/gems/3.3.0/gems/drum-0.2.3/lib/drum/service/spotify.rb:247:in `all_sp_library_playlists'
```

[Here](https://github.com/fwcd/drum/blob/e81081990ba094f9ed5a17f7a33e4e22ece33652/lib/drum/service/spotify.rb#L247) is the relevant library call.

**Comment by thepavangollapalli** [comment]
This seems to be because Spotify started returning `nil` as part of the list of playlists returned by the [get user playlists endpoint](https://developer.spotify.com/documentation/web-api/reference/get-list-users-playlists). 
```
 "items"=>[nil, {valid playlist object}, {valid playlist object}, ...]
 ```
The library expects `response['items']` to only contain valid playlist objects and [passes them directly to Playlist.new to initialize](https://github.com/guilhermesad/rspotify/blob/d6a9198cb7def54391b0f824ec33e94fc89843d7/lib/rspotify/user.rb#L285). I was able to fix this locally by dropping `nil` values:
```
response['items'].compact.map { |i| Playlist.new i }
```
