### ISSUE TITLE
Getting unauthorized error from api.

### ISSUE THREAD

**Issue by thomasdziedzic** [guilhermesad/rspotify#75]
I wanted to extract a bunch of playlist information since my api search comes up with a lot of results.

```
RestClient::Unauthorized: 401 Unauthorized
/usr/local/bundle/gems/rest-client-1.8.0/lib/restclient/abstract_response.rb:74:in `return!'
/usr/local/bundle/gems/rest-client-1.8.0/lib/restclient/request.rb:495:in `process_result'
/usr/local/bundle/gems/rest-client-1.8.0/lib/restclient/request.rb:421:in `block in transmit'
/usr/local/bundle/gems/rest-client-1.8.0/lib/restclient/request.rb:413:in `transmit'
/usr/local/bundle/gems/rest-client-1.8.0/lib/restclient/request.rb:176:in `execute'
/usr/local/bundle/gems/rest-client-1.8.0/lib/restclient/request.rb:41:in `execute'
/usr/local/bundle/gems/rest-client-1.8.0/lib/restclient.rb:65:in `get'
/usr/local/bundle/gems/rspotify-1.16.0/lib/rspotify/connection.rb:66:in `rescue in send_request'
/usr/local/bundle/gems/rspotify-1.16.0/lib/rspotify/connection.rb:61:in `send_request'
/usr/local/bundle/gems/rspotify-1.16.0/lib/rspotify/connection.rb:36:in `block (2 levels) in singleton class'
/usr/local/bundle/gems/rspotify-1.16.0/lib/rspotify/connection.rb:48:in `resolve_auth_request'
/usr/local/bundle/gems/rspotify-1.16.0/lib/rspotify/playlist.rb:236:in `tracks'
```

When I restart the script it continues working fine, so I don't think spotify is rate limiting me or preventing me from doing further call outs.

Looks like the exception is happening when it's trying to reauthenticate:
https://github.com/guilhermesad/rspotify/blob/485bbb0479fb9dbe518d9aaae41c2639fa0bc989/lib/rspotify/connection.rb#L66

**Comment by guilhermesad** [comment]
@thomasdziedzic could you paste the contents of your script? Wanted to know what calls exactly you're making.
